### ISSUE TITLE
RISE: boost_pool

### ISSUE THREAD

**Issue by ssadjina** [vekexasia/dpos-tools-data#10]
1. **Delegate Name**: boost_pool
2. **Share**: (variable)
3. **Payout schedule (weekly,daily,monthly)**: daily
4. **Min payout**: 1.0 RISE
5. **Fees included**: no
6. **Payout address (If different)**: 
7. **Pool Website**: http://rise-boost.the-viking.online/

As discussed earlier, this is a new pool concept which a.) increases the payouts of small to medium wallets (significantly) and b.) makes the payouts a bit less dependent on total pool weight for everybody.
This is achieved through a modification to the standard pool payout formula. Because of this, showing a share percent or a monthly payout estimate has little or no meaning. Instead, please link to the pool website and, if, possible use a button or symbol so it is clear to the dpostools user that this is a different system.

Thanks in advance, and if you have any question, please contact @The Viking on slack.

**Comment by vekexasia** [comment]
Can you remind me the formula here so that i can start thinking on it and see if i can eventually integrate it within the tool?

**Comment by ssadjina** [comment]
Sure!

![capture](https://user-images.githubusercontent.com/30830561/31884374-26e71c06-b7ed-11e7-8de3-a3d30ae0dd92.PNG)

Here p_i is the payout for voter i, P is the total payout amount (the amount to distribute over all voter wallets), N is the number of voters, k is the "Boost factor", x_i is the voting weight for voter i, and X is the total weight of the pool.

If k = 0%, we get the normal payout formula: p_i = P * x_i / X.
If we set k = 100%, every voter get's the exact same amount paid out: p_i = P / N.

I will probably start with k = 5%, which gives significant higher payouts for small wallets, yet only reduces large wallet payouts by a bit. I aim to tune k to obtain a nice balance: Too high, and the larger wallets will probably disappear, too low and it's just another "normal" pool.

An example of the payouts you would expect with k = 5% can be found on the [pool site](http://rise-boost.the-viking.online/). It also gives a bit more explanation.

But if you want to put that formula in, you can just set k = 0 for any normal pool, and you will get the same results.

What do you think?

**Comment by vekexasia** [comment]
:+1:

What is the current `P` in terms of percentage over forged blocks?

**Comment by ssadjina** [comment]
I am not 100% sure yet, but it'll probably be 80%.
