### ISSUE TITLE
OXY: viking_pool (website link)

### ISSUE THREAD

**Issue by ssadjina** [vekexasia/dpos-tools-data#13]
1. **Delegate Name**: viking_pool
2. **Share**: 35%
3. **Payout schedule (weekly,daily,monthly)**: daily
4. **Min payout**: 1.0 OXY
5. **Fees included**: no
6. **Payout address (If different)**: 
7. **Pool Website**: http://rise-boost.the-viking.online/

Hi!
Please include the pool website on OXY's dpostools list. Thanks!

**Comment by ssadjina** [comment]
Hi again!

Very sorry, I gave you the wrong link. The correct link for viking_pool (OXY) is http://oxy.the-viking.online/

Please change the next time you work on the setup here :)

**Comment by vekexasia** [comment]
argh :P

**Comment by PNWDrew** [comment]
Sorry about opening new issue. I didn't know the viking had a previous issue submitted. Bad team communications!

Delegate Name: viking_pool
Share: 50%
Payout schedule (weekly,daily,monthly): daily
Min payout: 1.0 OXY
Fees included: no
Payout address (If different):
Pool Website: http://oxy.the-viking.online/

**Comment by ssadjina** [comment]
Hi again, Andrea!

Please change _viking_pool_ in OXY to 50% shared (other details are in PNWDrew's comment above. Cheers!
