### ISSUE TITLE
SHIFT lancekincaid

### ISSUE THREAD

**Issue by lancekrogers** [vekexasia/dpos-tools-data#131]
1. **Delegate Name**:  lancekincaid
2. **Share**: 80%
3. **Payout schedule (weekly,daily,monthly)**: weekly
4. **Min payout**: 0.1 Shift
5. **Fees included**: no
6. **Payout address (If different)**: 
7. **Pool Website**: 
8. **Did you send a donation to BTC: `1kfNQjNx5uZRNbgx9fWrYC2Keo8Wpg6Pd` (yes or no)?**: no
9. **I am aware that not performing the donation could result in a long time and that I cannot stress vekexasia for not finding free time for doing it.**: Can you post a LTC address?

**Comment by vekexasia** [comment]
Hello @lancekrogers sorry for the late reply. Very busy nowadays.

here is my ltc addr => LNsFEp2Gue71prwvTSyXNBpPn6xEvfsRSm
