### ISSUE TITLE
Oxy: dutch_pool

### ISSUE THREAD

**Issue by dutchpool** [vekexasia/dpos-tools-data#15]
1. **Delegate Name**: dutch_pool / kippers / fnoufnou / st3v3n
2. **Share**: dutch_pool 90% / kippers, fnoufnouf, st3v3n 75%
3. **Payout schedule (weekly,daily,monthly)**: weekly
4. **Min payout**: 1.0 OXY
5. **Fees included**: no (fees are subtracted from the share)
6. **Payout address (If different)**: dutch_pool_payout / 1699926527705876107X
7. **Pool Website**: http://oxy.dutchpool.io

dutch_pool:
    tooltip: "dutch_pool member"
    tag: "DUTCH" (or "DUT" if DUTCH is too long)
    class: ?
    members:
      - dutch_pool
      - kippers
      - fnoufnou
      - st3v3n

Upgrade available:
kippers, fnoufnou and st3v3n share 75%. dutch_pool always shares 90%. If you vote for all four delegates, then kippers, fnoufnou and st3v3n also share 90% each.

**Comment by vekexasia** [comment]
Please open an issue for every member and respective share and tag and upgrades for each member. For now i'll add only dutch_pool at 90%
