### ISSUE TITLE
Please change my tag on liskbuilders

### ISSUE THREAD

**Issue by Samuray2016** [vekexasia/dpos-tools-data#172]
Hello!
Please change my tag on liskbuilders site from AFT to independent as I am no longer part of AFT since 1 year and 3 months now.. Thanks!

1. **Delegate Name**: samuray
2. **Share**: 50%
3. **Payout schedule (weekly,daily,monthly)**: weekly
4. **Min payout**: 1 LSK
5. **Fees included**: yes
6. **Payout address (If different)**: 6876894875185466854L
7. **Pool Website**: https://lisk.samuray.io/, http://lisk.samuray-pool.pw/
8. **Did you send a donation to BTC: `1kfNQjNx5uZRNbgx9fWrYC2Keo8Wpg6Pd` (yes or no)?**:
9. **I am aware that not performing the donation could result in a long time and that I cannot stress vekexasia for not finding free time for doing it.**:

**Comment by vekexasia** [comment]
looks like its not for dpos-tools-data. :)
