### ISSUE TITLE
LISK: dutch_pool

### ISSUE THREAD

**Issue by dutchpool** [vekexasia/dpos-tools-data#41]
1. **Delegate Name**: dutch_pool
2. **Share**: 90%
3. **Payout schedule (weekly,daily,monthly)**: weekly
4. **Min payout**: 1.0 Lisk
5. **Fees included**: no
6. **Payout address (If different)**: 14109631139463270334L
7. **Pool Website**: http://lisk.dutchpool.io

**Tag**: DUTCH

**Comment by dutchpool** [comment]
Thank you for adding dutch pool to your tool :)
Just a small correction, dutch_pool will always share 90% and doesn't have an upgrade

1. **Delegate Name**: dutch_pool
2. **Share**: 90%
3. **Payout schedule (weekly,daily,monthly)**: weekly
4. **Min payout**: 1.0 Lisk
5. **Fees included**: no
6. **Payout address (If different)**: 14109631139463270334L
7. **Pool Website**: http://lisk.dutchpool.io

**Tag**: DUTCH

**Comment by vekexasia** [comment]
So there is no need to vote for all?

Il 11 nov 2017 13:14, "dutchpool" <notifications@github.com> ha scritto:

**Comment by dutchpool** [comment]
Indeed, the delegate dutch_pool always shares 90%. But kippers, fnoufnou, thamar and st3v3n only share 90% each when you vote for all 5 delegates of dutch pool. By default those delegates share 75% each.

**Comment by sluit** [comment]
@vekexasia Do you still have this one in your view? :)
