### ISSUE TITLE
OXY - the_lottery

### ISSUE THREAD

**Issue by PNWDrew** [vekexasia/dpos-tools-data#42]
1. **Delegate Name**: the_lottery
2. **Share**: 70%
3. **Payout schedule (weekly,daily,monthly)**: weekly
4. **Min payout**: None
5. **Fees included**: yes
6. **Payout address (If different)**: 
7. **Pool Website**:

**Comment by vekexasia** [comment]
Is this a lottery where some winners get elected? If so can you explain?

**Comment by PNWDrew** [comment]
Hi Vekecasia,

Yes it is a lottery as you surmised. Probably way too much to explain on
dpostools. We're  making a site to explain in detail. Got a large voter
that bumped us into forging sooner than expected.

2 drawings per week, 3 winners each drawing. #1 is 225 OXY, #2 is 75, #3 is
25. Also 25 OXY donated to oxy support address per drawing. 70% paid out
per week. Our ads in Slack have the details on most of them.

We may alter it to increase payouts though, so for short term maybe just
list 70% per week and we'll get details on our site ASAP.

You can also dm @The Viking on slack or hold off on listing any details
beyond the 70% until we run remaining tests on his formula for odds. I'll
try to reach him to see how that's going. For the short term it's 70% paid
out between prizes and donations.

Thanks for the prompt reply and the work you do on the site to help voters.
Andrew
@pnwdrew on Slack
