### ISSUE TITLE
LISK: dutch_pool

### ISSUE THREAD

**Issue by dutchpool** [vekexasia/dpos-tools-data#43]
Thank you for adding dutch pool to your tool :)
Just a small correction, dutch_pool will always share 90% and doesn't have an upgrade

1. **Delegate Name**: dutch_pool
2. **Share**: 90%
3. **Payout schedule (weekly,daily,monthly)**: weekly
4. **Min payout**: 1.0 Lisk
5. **Fees included**: no
6. **Payout address (If different)**: 14109631139463270334L
7. **Pool Website**: http://lisk.dutchpool.io

**Tag**: DUTCH

**Comment by vekexasia** [comment]
Please comment on the other issue so that we keep the history of each delegate on one single thread. I am closing this one
