### ISSUE TITLE
Lisk - endro

### ISSUE THREAD

**Issue by endro42** [vekexasia/dpos-tools-data#44]
1. **Delegate Name**: endro
2. **Share**: 45
3. **Payout schedule (weekly,daily,monthly)**: weekly
4. **Min payout**: 1.0 LSK
5. **Fees included**: no
6. **Payout address (If different)**: 8407898697244251964L
7. **Pool Website**:

**Comment by tomploem** [comment]
@vekexasia Are these properties enough or should i add something else?

**Comment by endro42** [comment]
While the issue is closed i can not see my entry in the list on https://dpostools.com/LISK
