### ISSUE TITLE
Please raise viking_pool to 50% share in OXY

### ISSUE THREAD

**Issue by PNWDrew** [vekexasia/dpos-tools-data#45]
1. **Delegate Name**: viking_pool
2. **Share**: 50%
3. **Payout schedule (weekly,daily,monthly)**: Daily
4. **Min payout**: 1.0
5. **Fees included**: No
6. **Payout address (If different)**: 
7. **Pool Website**: oxy.the-viking.online

**Comment by vekexasia** [comment]
Please comment on your previous issue. do not open more issues for same delegate+coin pair.
