### ISSUE TITLE
Modify sharing percentage to 65%

### ISSUE THREAD

**Issue by ilie156** [vekexasia/dpos-tools-data#47]
1. **Delegate Name**: ilie_156
2. **Share**: 65
3. **Payout schedule (weekly,daily,monthly)**: weekly
4. **Min payout**: 1
5. **Fees included**: No
6. **Payout address (If different)**: ilie_156_rewards
7. **Pool Website**: ilie156.myoxy.pw
Please modify my sharing percentage from 50 to 65%
Thank you!

**Comment by vekexasia** [comment]
Please do not open new issues: Comment and *reopen* the other one #27
