### ISSUE TITLE
SHIFT - neuthor

### ISSUE THREAD

**Issue by Neuthor** [vekexasia/dpos-tools-data#48]
1. **Delegate Name**: Neuthor
2. **Share**: 40
3. **Payout schedule (weekly,daily,monthly)**: weekly
4. **Min payout**: 0.1
5. **Fees included**: Yes
6. **Pool Website**: neuthor.site

**Comment by vekexasia** [comment]
:)

**Comment by Neuthor** [comment]
Thanks

**Comment by vekexasia** [comment]
hmm ? @Neuthor ?
