### ISSUE TITLE
shift - shift_tools

### ISSUE THREAD

**Issue by shideneyu** [vekexasia/dpos-tools-data#52]
1. **Delegate Name**: shift_tools
2. **Share**: 35%
3. **Payout schedule (weekly,daily,monthly)**: monthly
4. **Min payout**: 0.01
5. **Fees included**:  yes
6. **Payout address (If different)**: 
7. **Pool Website**: https://shift-tools.com/pool.html
8. **Notes**: Depending on the month, the payout is either a lottery that rewards with physical gifts, or a the entirety of the bounty.

**Comment by TerraBellus** [comment]
There is no evidence, that I am aware of, that the pool, shift_tools, is paying out in any manner. Outgoing transactions are consistently sent to Bittrex directly, or via one other address (with a transaction on to Bittrex the same day). A share percentage of 0%, or removal of the pool entirely, would seem to more accurately represent their payout.

I am a community member, unassociated with shift_tools.

**Comment by shideneyu** [comment]
Hi, I'm currently fixing the website, I am currently working in it to push on phantom . The payout was in form of a tombola.

**Comment by TerraBellus** [comment]
Am I right in thinking that all/any of your pool's payouts must have taken place off chain? If so, would you agree that your verifiable share is currently 0%?
