### ISSUE TITLE
OXY - gregoro

### ISSUE THREAD

**Issue by gregooroo** [vekexasia/dpos-tools-data#7]
1. **Delegate Name**: gregoro
2. **Share**: 50%
3. **Payout schedule (weekly,daily,monthly)**: daily
4. **Min payout**: 1
5. **Fees included**: no
6. **Payout address (If different)**: ----
7. **Pool Website**: https://pool.oxycoin.gregoro.top/

**Comment by gregooroo** [comment]
2. Share: 75%
7. Pool Website: https://pool.oxycoin.gregoro.top/  (It's not included in dpostools webiste)

**Comment by vekexasia** [comment]
Damn it i forgot the website. sorry.

**Comment by gregooroo** [comment]
That's ok :) It can wait.
