### ISSUE TITLE
OXY djandre pool

### ISSUE THREAD

**Issue by djandre77** [vekexasia/dpos-tools-data#73]
1. **Delegate Name**: djandre
2. **Share**: 80%
3. **Payout schedule (weekly,daily,monthly)**: daily
4. **Min payout**: 1
5. **Fees included**: yes
6. **Payout address (If different)**: djandre
7. **Pool Website**: www.oxypool.ovh

**Comment by djandre77** [comment]
Hi, Andrea. I do not see any changes ...

Delegate Name: djandre
Share: 80%
Payout schedule (weekly,daily,monthly): daily
Min payout: 1
Fees included: yes
Payout address (If different): djandre
Pool Website: www.oxypool.ovh

**Comment by djandre77** [comment]
Share not 36.6%.
Share 80%.

**Comment by vekexasia** [comment]
it's 80%. did you clean your browser cache?

**Comment by djandre77** [comment]
Thanks. It is ok(clean your browser cache)
